version: '3'

services:
  localdb:
    container_name: example_db
    image: mysql:8.0.23
    platform:  linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: test
      MYSQL_DATABASE: db
      MYSQL_PASSWORD: password

  app:
    container_name: example_api
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    environment:
      - ENV=dev
    command: bash -c "python run_app.py"
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - localdb
    links:
      - localdb
